name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.name${{secrets.USER_NAME}}
          git config --global user.email${{secrets.USER_EMAIL}}
          git remote set-url origin https://${{secrets.ACCESS_TOKEN)}@github.com/${{secrets.USER_NAME}}/CymotiveChallenge
          npm run deploy
